
const CREATE_LISTING = 'CREATE_LISTING';
const CREATE_LISTING_SUCCESS = 'AUTHENTICATE_SUCCESS';
const CREATE_LISTING_FAILURE = 'CREATE_LISTING_FAILURE';

export default {
    CREATE_LISTING,
    CREATE_LISTING_SUCCESS,
    CREATE_LISTING_FAILURE,
};