const GET_LISTING = 'GET_LISTING';
const GET_LISTING_SUCCESS = 'GET_LISTING_SUCCESS';
const GET_LISTING_FAILURE = 'GET_LISTING_FAILURE';

const GET_LISTINGS = 'GET_LISTINGS';
const GET_LISTINGS_SUCCESS = 'GET_LISTINGS_SUCCESS';
const GET_LISTINGS_FAILURE = 'GET_LISTINGS_FAILURE';

const GET_ADMIN_LISTINGS = 'GET_ADMIN_LISTINGS';
const GET_ADMIN_LISTINGS_SUCCESS = 'GET_ADMIN_LISTINGS_SUCCESS';
const GET_ADMIN_LISTINGS_FAILURE = 'GET_ADMIN_LISTINGS_FAILURE';

const CREATE_LISTING = 'CREATE_LISTING';
const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS';
const CREATE_LISTING_FAILURE = 'CREATE_LISTING_FAILURE';

const UPDATE_LISTING = 'UPDATE_LISTING';
const UPDATE_LISTING_SUCCESS = 'UPDATE_LISTING_SUCCESS';
const UPDATE_LISTING_FAILURE = 'UPDATE_LISTING_FAILURE';

const DELETE_LISTING = 'DELETE_LISTING';
const DELETE_LISTING_SUCCESS = 'DELETE_LISTING_SUCCESS';
const DELETE_LISTING_FAILURE = 'DELETE_LISTING_FAILURE';

export default {
    GET_LISTING,
    GET_LISTING_SUCCESS,
    GET_LISTING_FAILURE,
    GET_LISTINGS,
    GET_LISTINGS_SUCCESS,
    GET_LISTINGS_FAILURE,
    GET_ADMIN_LISTINGS,
    GET_ADMIN_LISTINGS_SUCCESS,
    GET_ADMIN_LISTINGS_FAILURE,
    CREATE_LISTING,
    CREATE_LISTING_SUCCESS,
    CREATE_LISTING_FAILURE,
    UPDATE_LISTING,
    UPDATE_LISTING_SUCCESS,
    UPDATE_LISTING_FAILURE,
    DELETE_LISTING,
    DELETE_LISTING_SUCCESS,
    DELETE_LISTING_FAILURE
};