const GET_LISTING = 'GET_LISTING';
const GET_LISTING_SUCCESS = 'GET_LISTING_SUCCESS';
const GET_LISTING_FAILURE = 'GET_LISTING_FAILURE';

const GET_LISTINGS = 'GET_LISTINGS';
const GET_LISTINGS_SUCCESS = 'GET_LISTINGS_SUCCESS';
const GET_LISTINGS_FAILURE = 'GET_LISTINGS_FAILURE';

const GET_LATEST_LISTINGS = 'GET_LATEST_LISTINGS';
const GET_LATEST_LISTINGS_SUCCESS = 'GET_LATEST_LISTINGS_SUCCESS';
const GET_LATEST_LISTINGS_FAILURE = 'GET_LATEST_LISTINGS_FAILURE';

const GET_FEATURED_LISTINGS = 'GET_FEATURED_LISTINGS';
const GET_FEATURED_LISTINGS_SUCCESS = 'GET_FEATURED_LISTINGS_SUCCESS';
const GET_FEATURES_LISTINGS_FAILURE = 'GET_FEATURES_LISTINGS_FAILURE';

const GET_USER_LISTINGS = 'GET_USER_LISTINGS';
const GET_USER_LISTINGS_SUCCESS = 'GET_USER_LISTINGS_SUCCESS';
const GET_USER_LISTINGS_FAILURE = 'GET_USER_LISTINGS_FAILURE';

const CREATE_LISTING = 'CREATE_LISTING';
const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS';
const CREATE_LISTING_FAILURE = 'CREATE_LISTING_FAILURE';

const UPDATE_LISTING = 'UPDATE_LISTING';
const UPDATE_LISTING_SUCCESS = 'UPDATE_LISTING_SUCCESS';
const UPDATE_LISTING_FAILURE = 'UPDATE_LISTING_FAILURE';

export default {
    GET_LISTING,
    GET_LISTING_SUCCESS,
    GET_LISTING_FAILURE,
    GET_LISTINGS,
    GET_LISTINGS_SUCCESS,
    GET_LISTINGS_FAILURE,
    GET_LATEST_LISTINGS,
    GET_LATEST_LISTINGS_SUCCESS,
    GET_LATEST_LISTINGS_FAILURE,
    GET_FEATURED_LISTINGS,
    GET_FEATURED_LISTINGS_SUCCESS,
    GET_FEATURES_LISTINGS_FAILURE,
    GET_USER_LISTINGS,
    GET_USER_LISTINGS_SUCCESS,
    GET_USER_LISTINGS_FAILURE,
    CREATE_LISTING,
    CREATE_LISTING_SUCCESS,
    CREATE_LISTING_FAILURE,
    UPDATE_LISTING,
    UPDATE_LISTING_SUCCESS,
    UPDATE_LISTING_FAILURE
};