const OPEN_NEW_LISTING_MODAL = 'OPEN_NEW_LISTING_MODAL';
const CLOSE_NEW_LISTING_MODAL = 'CLOSE_NEW_LISTING_MODAL';
const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL';
const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL';

export default {
    OPEN_NEW_LISTING_MODAL,
    CLOSE_NEW_LISTING_MODAL,
    OPEN_AUTH_MODAL,
    CLOSE_AUTH_MODAL
}