
const AUTHENTICATE = 'AUTHENTICATE';
const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
const AUTHENTICATE_FAILURE  = 'AUTHENTICATE_FAILURE';
const UNAUTHENTICATE = 'UNAUTHENTICATE';

const VERIFY_TOKEN = 'VERIFY_TOKEN';
const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
const VERIFY_TOKEN_FAILURE  = 'VERIFY_TOKEN_FAILURE';

const REGISTER = 'REGISTER';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE  = 'REGISTER_FAILURE';

export default {
    AUTHENTICATE,
    AUTHENTICATE_SUCCESS,
    AUTHENTICATE_FAILURE,
    UNAUTHENTICATE,
    VERIFY_TOKEN_SUCCESS,
    VERIFY_TOKEN_FAILURE, 
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAILURE
};