const CREATE_RENT_REQUEST = 'CREATE_RENT_REQUEST';
const CREATE_RENT_REQUEST_SUCCESS = 'CREATE_RENT_REQUEST_SUCCESS';
const CREATE_RENT_REQUEST_FAILURE = 'CREATE_RENT_REQUEST_FAILURE';

export default {
    CREATE_RENT_REQUEST,
    CREATE_RENT_REQUEST_SUCCESS,
    CREATE_RENT_REQUEST_FAILURE
};