const GET_BUSINESSES = 'GET_BUSINESSES';
const GET_BUSINESSES_SUCCESS = 'GET_BUSINESSES_SUCCESS';
const GET_BUSINESSES_FAILURE = 'GET_BUSINESSES_FAILURE';

const GET_BUSINESS = 'GET_BUSINESS';
const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';

const GET_BUSINESS_LISTINGS = 'GET_BUSINESS_LISTINGS';
const GET_BUSINESS_LISTINGS_SUCCESS = 'GET_BUSINESS_LISTINGS_SUCCESS';

export default {
    GET_BUSINESSES,
    GET_BUSINESSES_SUCCESS,
    GET_BUSINESSES_FAILURE,
    GET_BUSINESS,
    GET_BUSINESS_SUCCESS,
    GET_BUSINESS_LISTINGS,
    GET_BUSINESS_LISTINGS_SUCCESS
};