const GET_BUSINESSES = 'GET_BUSINESSES';
const GET_BUSINESSES_SUCCESS = 'GET_BUSINESSES_SUCCESS';
const GET_BUSINESSES_FAILURE = 'GET_BUSINESSES_FAILURE';

export default {
    GET_BUSINESSES,
    GET_BUSINESSES_SUCCESS,
    GET_BUSINESSES_FAILURE,
};