const GET_ACCOUNT = 'GET_ACCOUNT';
const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';

const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE';

export default {
    GET_ACCOUNT,
    GET_ACCOUNT_SUCCESS,
    UPDATE_ACCOUNT,
    UPDATE_ACCOUNT_SUCCESS,
    UPDATE_ACCOUNT_FAILURE
};