const GET_ACCOUNT = 'GET_ACCOUNT';
const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';

const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE';

const GET_BUSINESS = 'GET_BUSINESS';
const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';

const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
const UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS';
const UPDATE_BUSINESS_FAILURE = 'UPDATE_BUSINESS_FAILURE';

export default {
    GET_ACCOUNT,
    GET_ACCOUNT_SUCCESS,
    UPDATE_ACCOUNT,
    UPDATE_ACCOUNT_SUCCESS,
    UPDATE_ACCOUNT_FAILURE,
    GET_BUSINESS,
    GET_BUSINESS_SUCCESS,
    UPDATE_BUSINESS,
    UPDATE_BUSINESS_SUCCESS,
    UPDATE_BUSINESS_FAILURE
};